CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230708184818_Initial') THEN
    CREATE TABLE "Browser" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NULL,
        "ColumnDefinitions" text NULL,
        "GridOptions" text NULL,
        CONSTRAINT "PK_Browser" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230708184818_Initial') THEN
    CREATE TABLE "PaymentInfo" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PaymentType" integer NOT NULL,
        CONSTRAINT "PK_PaymentInfo" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230708184818_Initial') THEN
    CREATE TABLE "Product" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NULL,
        "Description" text NULL,
        "Image" bytea NULL,
        "CreationDate" timestamp with time zone NOT NULL DEFAULT (CURRENT_DATE),
        "ModificationDate" timestamp with time zone NOT NULL DEFAULT (CURRENT_DATE),
        CONSTRAINT "PK_Product" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230708184818_Initial') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserName" text NULL,
        "ModificationDate" timestamp with time zone NOT NULL,
        "CreationDate" timestamp with time zone NOT NULL,
        "PasswordHash" bytea NULL,
        "PasswordSalt" bytea NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230708184818_Initial') THEN
    CREATE TABLE "VatRate" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NULL,
        "Percent" text NULL,
        CONSTRAINT "PK_VatRate" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230708184818_Initial') THEN
    CREATE TABLE "ProductProperties" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NULL,
        "Value" text NULL,
        "ProductId" integer NULL,
        CONSTRAINT "PK_ProductProperties" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProductProperties_Product_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Product" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230708184818_Initial') THEN
    CREATE TABLE "CompanyInfo" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CompanyName" text NULL,
        "CompanyType" integer NOT NULL,
        "Address" text NULL,
        "City" text NULL,
        "PostalCode" text NULL,
        "Nip" text NULL,
        "Created" timestamp with time zone NOT NULL,
        "AppUserId" integer NULL,
        CONSTRAINT "PK_CompanyInfo" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CompanyInfo_Users_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES "Users" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230708184818_Initial') THEN
    CREATE TABLE "UserInfo" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FirstName" text NULL,
        "LastName" text NULL,
        "Address" text NULL,
        "City" text NULL,
        "PostalCode" text NULL,
        "UserId" integer NOT NULL,
        CONSTRAINT "PK_UserInfo" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UserInfo_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230708184818_Initial') THEN
    CREATE TABLE "UserRole" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Role" integer NOT NULL,
        "UserId" integer NOT NULL,
        CONSTRAINT "PK_UserRole" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UserRole_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230708184818_Initial') THEN
    CREATE TABLE "Receipt" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ReceiptNumber" text NULL,
        "ShopId" integer NULL,
        "Total" text NULL,
        "Created" timestamp with time zone NOT NULL,
        "PaymentInfoId" integer NULL,
        "AppUserId" integer NULL,
        CONSTRAINT "PK_Receipt" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Receipt_CompanyInfo_ShopId" FOREIGN KEY ("ShopId") REFERENCES "CompanyInfo" ("Id"),
        CONSTRAINT "FK_Receipt_PaymentInfo_PaymentInfoId" FOREIGN KEY ("PaymentInfoId") REFERENCES "PaymentInfo" ("Id"),
        CONSTRAINT "FK_Receipt_Users_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES "Users" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230708184818_Initial') THEN
    CREATE TABLE "ReceiptPosition" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NULL,
        "Description" text NULL,
        "Amount" text NULL,
        "Quantity" integer NOT NULL,
        "ProductId" integer NULL,
        "VatRateId" integer NULL,
        "ReceiptId" integer NULL,
        CONSTRAINT "PK_ReceiptPosition" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ReceiptPosition_Product_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Product" ("Id"),
        CONSTRAINT "FK_ReceiptPosition_Receipt_ReceiptId" FOREIGN KEY ("ReceiptId") REFERENCES "Receipt" ("Id"),
        CONSTRAINT "FK_ReceiptPosition_VatRate_VatRateId" FOREIGN KEY ("VatRateId") REFERENCES "VatRate" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230708184818_Initial') THEN
    INSERT INTO "Users" ("Id", "CreationDate", "ModificationDate", "PasswordHash", "PasswordSalt", "UserName")
    VALUES (1, TIMESTAMPTZ '-infinity', TIMESTAMPTZ '-infinity', BYTEA E'\\x8DE86070787A813ED9C7C4912054B307B08B0B6CDB3D223FDF4B82D35FE5B9018D4C8E6FE62E2754987CB6BC6074B507904F81323FDC957D78C301F71814B3C1', BYTEA E'\\xE927F3BC3CD368B83C1EFC889EC8687C21CF82A20AEA657AD769122EE3149AF8A4307E9ED6EB537BAEE1040CC8CB07A932A60EB5F57FD59A7F5EC7EC3001D68BD2A1E47B72EA4E0B854DA85998C710821F67FEB8759A5707263E4437786711DE4A44DDB3FF61E9D2B7DD3F5271BB8A1EA75C7FADEB242AE9A34CCDEB675518BD', 'Admin');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230708184818_Initial') THEN
    INSERT INTO "UserInfo" ("Id", "Address", "City", "FirstName", "LastName", "PostalCode", "UserId")
    VALUES (1, '', '', 'Admin', '', '', 1);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230708184818_Initial') THEN
    INSERT INTO "UserRole" ("Id", "Role", "UserId")
    VALUES (1, 1, 1);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230708184818_Initial') THEN
    CREATE INDEX "IX_CompanyInfo_AppUserId" ON "CompanyInfo" ("AppUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230708184818_Initial') THEN
    CREATE INDEX "IX_ProductProperties_ProductId" ON "ProductProperties" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230708184818_Initial') THEN
    CREATE INDEX "IX_Receipt_AppUserId" ON "Receipt" ("AppUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230708184818_Initial') THEN
    CREATE INDEX "IX_Receipt_PaymentInfoId" ON "Receipt" ("PaymentInfoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230708184818_Initial') THEN
    CREATE INDEX "IX_Receipt_ShopId" ON "Receipt" ("ShopId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230708184818_Initial') THEN
    CREATE INDEX "IX_ReceiptPosition_ProductId" ON "ReceiptPosition" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230708184818_Initial') THEN
    CREATE INDEX "IX_ReceiptPosition_ReceiptId" ON "ReceiptPosition" ("ReceiptId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230708184818_Initial') THEN
    CREATE INDEX "IX_ReceiptPosition_VatRateId" ON "ReceiptPosition" ("VatRateId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230708184818_Initial') THEN
    CREATE UNIQUE INDEX "IX_UserInfo_UserId" ON "UserInfo" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230708184818_Initial') THEN
    CREATE INDEX "IX_UserRole_UserId" ON "UserRole" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230708184818_Initial') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Users"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Users") + 1,
            nextval(pg_get_serial_sequence('"Users"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"UserInfo"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "UserInfo") + 1,
            nextval(pg_get_serial_sequence('"UserInfo"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"UserRole"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "UserRole") + 1,
            nextval(pg_get_serial_sequence('"UserRole"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230708184818_Initial') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20230708184818_Initial', '6.0.0');
    END IF;
END $EF$;
COMMIT;

